### PR TITLE
Implement `expect_depends()` (closes #40)

### LINKED ISSUE #40: Implement functional dependency expectation
If X functionally determines Y, then each X value is associated with precisely one Y value. For example:

```r
# Check that E461 and E462 are determined by E307
expect_determined(vars(E461, E462), by = E307) 
```
https://en.wikipedia.org/wiki/Functional_dependency

### PR DESCRIPTION
**Pull request by kinto-b**

### CODE REVIEW

**Review by gorcha — APPROVED** [review]
Looks good! Only comment is that the docs could be a little clearer on the purpose/use case. The functional dependency thing is technically correct but it could do a with more plain language explanation of use cases (probs just an extra short paragraph).

**Comment by kinto-b** [comment]
@gorcha Can't really think what to add. How about just adding this sentence:

> One set of variables, X, functionally depends on another, Y, iff each value
> in Y corresponds to exactly one value in X. For instance, `course_duration`
> and `course_topic` functionally depend on `course_code` if each `course_code`
> corresponds to just one combination of `course_duration` and `course topic`.
> **That is, if two records have the same `course_code` then they must have the
> same `course_duration` and `course_topic`.**

**Comment by gorcha** [comment]
Yeah I think that should do it. Also would recommend replacing "iff" with "if and only if" for clarity.

**Comment by kinto-b** [comment]
@gorcha Sweet :) 

Also what's the best way to handle multiple branches? I'm assuming if I update the NEWS/version on this branch as well, I'll generate a merge conflict. Should I just leave as is and update on the main branch after squash/merge?

**Comment by gorcha** [comment]
Nah just update on the branch and you should be able to resolve merge conflicts in the squash/merge commit.

**Pull request merged**
