### PR TITLE
Remove non-printable chars from excel output (closes #56)

### LINKED ISSUE #56: `output_results_excel ` writes a corrupted excel file
Just ran into this with GOS. 

```
x <- test_dir(full_path, stop_on_failure = FALSE, stop_on_warning = FALSE)

res_path <- paste0(full_path, "/results_pop_final_clean.xlsx")
output_results_excel(x, res_path)
```

One of the base checks had a reference to `E386` which is no longer in the data. This resulted in the base check spitting out an error:
```
`Problem with `mutate()` input `..1`. [31mx[39m object 'E386' not found [34mi[39m Input `..1` is `!E386 %in% c(NA, "", 9)`.`
```

`test_dir` didn't actually stop due to this error, and the output produced is a corrupted excel file with a blank sheet like so
image

Obviously there _should_ be no errors in the first place when running unit tests, but it could be useful to still be able to access the output somehow to quickly diagnose the issue. In a CSV, the error is output.
image

We could also just have it such that `output_results_excel` spits an error and doesn't run if there are any errors in the tests (probably the simplest solution)

### PR DESCRIPTION
**Pull request by kinto-b**
Certain non-printable characters produced in R error messages were corrupting the excel output

### CODE REVIEW

**Review by gorcha — CHANGES_REQUESTED** [review]
Hey!

This all looks good, but I'm not sure that this is the best approach.

For one thing when trying to remove non-printable characters it's better to use the character class rather than an explicit range, so you can be sure it'll properly support non-ASCII encodings (i.e. `"[^[:print:]]"`).

I'm also thinking a more direct approach might be better (and cleaner) - since we're specifically having issues with ANSI control codes we can just target them. Fortunately crayon has a function that does this:
```r
description = crayon::strip_style(str_replace_all(d$message, "[[:space:]]", " "))
```

On other minor thing, also needs the version bumped to dev and a news bullet added.

**Comment by kinto-b** [comment]
Ahh, I didn't know about `strip_style()`. That's great. Definitely to be preferred

**Comment by kinto-b** [comment]
I'll make that change now

**Review by gorcha — APPROVED** [review]

**Comment by gorcha** [comment]
Looking good!

**Pull request merged**
